Drop support for EOL Python versions, add 3.6, fix failing tests.
spoqa/sqlalchemy-utc pull request #2
Opened 2018-01-19 06:31 UTC by gwax

I have some features that I would like to contribute to your package for use downstream. This PR updates the versions of Python and other libraries used in testing and adjusts how tests are performed. This PR does not change package functionality.

2018-01-19 09:59 UTC, dahlia requested changes
Thanks for your contribution.  It would be great if some adjustments are made.

2018-01-19 09:59 UTC, dahlia commented on .travis.yml
> +  - codecov
Could you maintain the style as it was as possible (such as no indent for list bullets)?  The diff is unnecessarily complex so that I could hardly track the actual changes.

2018-01-19 09:59 UTC, dahlia commented on sqlalchemy_utc.py
> +__version__ = '0.9.1'
If we're going to drop older versions of Python and SQLAlchemy we'd better bump its minor version, i.e., 0.10.0 instead of 0.9.1.

2018-01-19 18:05 UTC, gwax commented on sqlalchemy_utc.py
> +__version__ = '0.9.1'
Done.

2018-01-19 18:20 UTC, gwax commented on .travis.yml
> +  - codecov
Done.

2018-01-20 06:47 UTC, dahlia approved these changes

2018-01-20 06:47 UTC, merged

2018-01-20 06:47 UTC, dahlia commented
Thanks!